# Generated by Django 5.2 on 2025-04-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_dishtype',
            old_name='type_name',
            new_name='dishtype_name',
        ),
        migrations.CreateModel(
            name='tbl_ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=50, unique=True)),
                ('ingredient_description', models.TextField(blank=True, null=True)),
                ('ingredient_photo', models.FileField(blank=True, null=True, upload_to='ingredients/')),
                ('ingredient_qty', models.IntegerField(blank=True, null=True)),
                ('ingredient_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_dish')),
            ],
        ),
    ]
