# Generated by Django 5.2 on 2025-04-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_type_name_tbl_dishtype_dishtype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_ingredients',
            name='ingredient_name',
            field=models.CharField(max_length=50),
        ),
    ]
