# Generated by Django 5.2 on 2025-04-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_tbl_ingredients_ingredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_plan',
            old_name='name',
            new_name='plan_name',
        ),
    ]
