# Generated by Django 5.2 on 2025-04-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('user_first_name', models.CharField(max_length=150)),
                ('user_last_name', models.CharField(max_length=150)),
                ('user_phone', models.CharField(max_length=15, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_status', models.IntegerField(default=0)),
                ('user_photo', models.FileField(blank=True, null=True, upload_to='user_photos/')),
            ],
        ),
    ]
