# Generated by Django 5.2 on 2025-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='password',
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='user_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
