# Generated by Django 5.2 on 2025-04-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_remove_tbl_user_password_tbl_user_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_phone',
            field=models.CharField(max_length=15),
        ),
    ]
