# Generated by Django 5.2 on 2025-04-16 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_tbl_user_user_email_alter_tbl_user_user_phone'),
        ('User', '0004_tbl_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_chat',
            name='user_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user'),
        ),
    ]
